language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements/development.txt
# command to run tests
script:
  - make test