# Generated by Django 3.0.6 on 2020-05-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitlinkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitly.Bitlink')),
            ],
        ),
    ]
