# Generated by Django 3.0.6 on 2020-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('thumbnail_image_url', models.URLField()),
                ('original_url', models.URLField()),
            ],
        ),
    ]
