# Generated by Django 3.0.6 on 2020-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonblog', '0002_naverpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverpost',
            name='keyword',
            field=models.CharField(default='기록없음', max_length=16),
            preserve_default=False,
        ),
    ]
